task: squadv2_context_gain
class: !function context_gain.ContextGain

dataset_path: json
dataset_kwargs:
  data_files:
    test: /lustre1/work/c30897/wtq/projects/knowledge_decoupling/input/evaluate_data/jsonl/squadv2/test.jsonl

test_split: test

output_type: loglikelihood

metadata:
  version: 1.0