qsub squadv2_1_3.sh
qsub squadv2_5_9.sh
qsub triviaqa_rc_context_7_9.sh
qsub triviaqa_rc_context_1_5.sh
qsub triviaqa_rc_nocontext_7_9.sh
qsub triviaqa_rc_nocontext_1_5.sh
qsub xsum_7_9.sh
qsub xsum_1_5.sh
qsub cnn_dailymail_1_5.sh
qsub cnn_dailymail_7_9.sh