# configs/train.yaml

data:
  paths: []
  limit: []

model:
  config: null
  init_model: null
  checkpoint: null

training:
  epochs: 3
  learning_rate: 5e-5
  eval_strategy: "no"

checkpointing:
  checkpoints_per_epoch: 50
  save_checkpoints_num: 2

runtime:
  speedup: false

output:
  path: null

hydra:
  run:
    dir: ${output.path}