# configs/train.yaml
base:
  path: /home/pj24001974/ku50001571/projects/knowledge_decoupling

model:
  config: Qwen/Qwen3.5-0.8B-Base
  init_model: null
  checkpoint: null

data:
  name: SmolLM2-135M-20B-bs1024
  paths:
    - ${base.path}/input/tokenized/${model.config}/train/${data.name}
  limit: 
    - 0

training:
  epochs: 1
  batch_size: 1
  learning_rate: 2e-4
  eval_strategy: "no"
  checkpoints_per_epoch: 50
  save_checkpoints_num: 2
  attn_implementation: "sdpa"

output:
  path: ${base.path}/output/${model.config}/${data.name}/base-ep${training.epochs}-lr${training.learning_rate}

hydra:
  run:
    dir: ${output.path}