import os
from pathlib import Path

project_base_path = os.getenv("PROJECT_BASE_PATH")
config_path = Path(project_base_path) / "config" / "eval_tasks" / "ewok"
config_path.mkdir(parents=True, exist_ok=True)
data_path = Path(project_base_path) / "input" / "evaluate_data" / "jsonl" / "ewok"

for dn in os.listdir(data_path):
    domain = dn.split(".")[0]
    print(f"Generating config for {domain}")
    with open(config_path / f"{domain}.yaml", 'w') as outfile:
        outfile.write(f"# generated by generate_ewok_config.py\ndataset_kwargs:\n  data_files: {data_path}/{dn}\ninclude: _template_yaml\ntask: ewok_{domain}\n")