# configs/train.yaml
base:
  path: 

model:
  config: null
  randomly_init_model: false
  checkpoint: null
  keep_n_layers: 5
  reset_top_layer: false
  tokenizer: openai-community/gpt2

data:
  name: 
  paths:
    - ${base.path}/input/tokenized/${model.config}/train/${data.name}
  limit: 
    - 0

finetune: false
training:
  epochs: 1
  batch_size: 4
  learning_rate: 2e-4
  eval_strategy: "no"
  checkpoints_per_epoch: 50
  save_checkpoints_num: 5
  attn_implementation: "sdpa"

output:
  path: ${model.config}/layers_${model.keep_n_layers}/base

hydra:
  run:
    dir: ${output.path}