# configs/train.yaml
base:
  path: /home/pj24001974/ku50001571/projects/knowledge_decoupling

model:
  config: openai-community/gpt2
  init_model: null
  checkpoint: null
  keep_n_layers: 5
  reset_top_layer: false

data:
  name: SmolLM2-135M-20B-nonce-bs4096
  paths:
    - ${base.path}/input/tokenized/${model.config}/train/${data.name}
  limit: 
    - 0

finetune: false
training:
  epochs: 1
  batch_size: 4
  learning_rate: 2e-4
  eval_strategy: "no"
  checkpoints_per_epoch: 50
  save_checkpoints_num: 5
  attn_implementation: "sdpa"

output:
  path: ${base.path}/output/${model.config}/toplayers_${model.keep_n_layers}/${data.name}/test

hydra:
  run:
    dir: ${output.path}